language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

before_install:
  - wget https://raw.githubusercontent.com/noonmaru/travis-ci-buildtools/master/buildtools.sh
  - chmod +x buildtools.sh
  - ./buildtools.sh 1.16.4
  - chmod +x ./gradlew

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'

script:
  - ./gradlew clean test